weather:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: dbt_sprite
      threads: 1
      type: postgres
      user: postgres

    prodution:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: prod
      threads: 1
      type: postgres
      user: postgres

  target: dev
